# Generated by Django 4.2.30 on 2026-04-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(unique=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordine', models.TextField(default='CURRENT_TIMESTAMP')),
                ('stato', models.TextField(choices=[('in_attesa', 'In Attesa'), ('in_preparazione', 'In Preparazione'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='in_attesa')),
                ('totale', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdineProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'ordine_prodotto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('prezzo', models.FloatField()),
                ('disponibile', models.IntegerField(default=1)),
                ('immagine_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prodotto',
                'managed': False,
            },
        ),
    ]
